#!/bin/sh
OPTION=""
xprop -name Emacs >/dev/null 2>/dev/null
if [ "$?" = "1" ]; then
    OPTION="$OPTION -c"
fi

xhost +si:localuser:$( whoami ) >&/dev/null && {
    OPTION="$OPTION -n"
} || {
     OPTION="$OPTION -t"
}

emacsclient $OPTION -a "" "$@"
